/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qihoo_mediasdk_codec_AMRWBDecoder */

#ifndef _Included_com_qihoo_mediasdk_codec_AMRWBDecoder
#define _Included_com_qihoo_mediasdk_codec_AMRWBDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qihoo_mediasdk_codec_AMRWBDecoder
 * Method:    open
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_qihoo_mediasdk_codec_AMRWBDecoder_open
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_qihoo_mediasdk_codec_AMRWBDecoder
 * Method:    decode
 * Signature: ([BI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_qihoo_mediasdk_codec_AMRWBDecoder_decode
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_qihoo_mediasdk_codec_AMRWBDecoder
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_qihoo_mediasdk_codec_AMRWBDecoder_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
